import PlayerProps from "@/types/player.props";
import TeamProps from "@/types/teams.props";
import UserProps from "@/types/user.props";

export const user = {
  name: "Irfan Madar",
  isVerified: true,
  id: "asldfkj",
  dob: new Date("2000-06-15"),
  username: "irfanulmadar",
  phone: "9876543210",
  email: "irfan@example.com",
  matches: [
    {
      runs: 45,
      catches: 2,
      wickets: 1,
      runOuts: 0,
      category: "T20",
      match: "64f09ad5b1234567890abcde", // example ObjectId
    },
  ],
  teams: ["64f09ad5b1234567890ab111", "64f09ad5b1234567890ab222"],
  friends: ["64f09ad5b1234567890ab333", "64f09ad5b1234567890ab444"],
  profile: "https://res.cloudinary.com/irfanulmadar/image/upload/v1748732410/avatar17_hnznuz.jpg",
  channels: ["64f09ad5b1234567890ab555"],
  stats: {
    totalRuns: 1030,
    totalWickets: 58,
    totalMatches: 65,
    totalCatches: 34,
  },
  tournaments: ["64f09ad5b1234567890ab666"],
  requests: {
    friendRequests: ["64f09ad5b1234567890ab777"],
    tournamentRequests: [
      {
        tournament: "64f09ad5b1234567890ab666",
        sender: "64f09ad5b1234567890ab777",
      },
    ],
    teamRequests: [
      {
        team: "64f09ad5b1234567890ab222",
        sender: "64f09ad5b1234567890ab777",
      },
    ],
  },

  socialLinks: {
    facebook: "https://facebook.com/irfanmadar",
    instagram: "https://instagram.com/irfan.madar",
    twitter: "https://twitter.com/irfanmadar",
    youtube: "https://youtube.com/@irfanmadar",
  },
  tags: ["all-rounder", "right-handed", "fast-bowler"],
  address: {
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
  },
  location: {
    type: "Point",
    coordinates: [77.5946, 12.9716], // Longitude, Latitude for Bengaluru
  },
};

// const mockPlayers: PlayerProps[] = [
//   {
//     id: "p1",
//     username: "playerOne",
//     name: "Evelyn Carter",
//     dob: "1995-04-10",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/playerOne.png",
//     following: [],
//     follwers: [],
//     rank: "Gold",
//   },
//   {
//     id: "p2",
//     username: "playerTwo",
//     name: "Marcus Wright",
//     dob: "1997-09-22",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/playerTwo.png",
//     following: [],
//     follwers: [],
//     rank: "Platinum",
//   },
//   {
//     id: "p3",
//     username: "playerThree",
//     name: "Sophia Lee",
//     dob: "1996-12-15",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/playerThree.png",
//     following: [],
//     follwers: [],
//     rank: "Diamond",
//   },
//   {
//     id: "p4",
//     username: "playerFour",
//     name: "Daniel Kim",
//     dob: "1998-07-03",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/playerFour.png",
//     following: [],
//     follwers: [],
//     rank: "Silver",
//   },
// ];

// const mockUsers: UserProps[] = [
//   {
//     id: "u1",
//     username: "alice",
//     name: "Alice Johnson",
//     dob: "1995-05-12",
//     role: "admin",
//     teams: [],
//     avatar: "/avatars/alice.png",
//     following: ["u2", "u3"],
//     follwers: ["u3", "u4"], // note: typo matches your interface
//   },
//   {
//     id: "u2",
//     username: "bob",
//     name: "Bob Smith",
//     dob: "1998-11-23",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/bob.png",
//     following: ["u1"],
//     follwers: ["u1", "u4"],
//   },
//   {
//     id: "u3",
//     username: "charlie",
//     name: "Charlie Evans",
//     dob: "1992-03-10",
//     role: "fan",
//     teams: [],
//     avatar: "/avatars/charlie.png",
//     following: ["u1", "u2"],
//     follwers: ["u1"],
//   },
//   {
//     id: "u4",
//     username: "dave",
//     name: "Dave Lee",
//     dob: "2000-07-19",
//     role: "player",
//     teams: [],
//     avatar: "/avatars/dave.png",
//     following: [],
//     follwers: ["u2", "u3"],
//   },
// ];

export const mockTournaments = [
  {
    id: "tour-001",
    name: "Summer Cricket Bash",
    description: "Annual summer tournament for local clubs.",
    details: {
      season: 2024,
      maxTeams: 12,
      matchesPerTeam: 5,
      totalOvers: 20,
      minAge: 16,
      maxAge: 60,
      halfBoundary: true,
      location: "City Sports Ground",
    },
    teams: ["team-alpha", "team-beta"], // User and Friend 1 joined
    organizer: "user-001", // Organized by current user
    status: "ongoing",
    schedule: [],
    winner: null,
    runnerUp: null,
    stats: null,
  },
  {
    id: "tour-002",
    name: "Winter League Cup",
    description: "Competitive winter league.",
    details: {
      season: 2023,
      maxTeams: 8,
      matchesPerTeam: 3,
      totalOvers: 15,
      minAge: 18,
      maxAge: 55,
      halfBoundary: false,
      location: "North Park Arena",
    },
    teams: ["team-gamma"], // Friend 2 joined
    organizer: "user-004",
    status: "ongoing",
    schedule: [],
    winner: null,
    runnerUp: null,
    stats: null,
  },
  {
    id: "tour-003",
    name: "Spring Friendly Series",
    description: "Casual friendly matches.",
    details: {
      season: 2025,
      maxTeams: 16,
      matchesPerTeam: 4,
      totalOvers: 10,
      minAge: 10,
      maxAge: 80,
      halfBoundary: true,
      location: "Suburb Fields",
    },
    teams: ["team-delta"],
    organizer: "user-005",
    status: "scheduled",
    schedule: [],
    winner: null,
    runnerUp: null,
    stats: null,
  },
  {
    id: "tour-004",
    name: "Champions Challenge",
    description: "Elite teams compete for the title.",
    details: {
      season: 2024,
      maxTeams: 4,
      matchesPerTeam: 2,
      totalOvers: 25,
      minAge: 20,
      maxAge: 45,
      halfBoundary: false,
      location: "National Stadium",
    },
    teams: [],
    organizer: "user-006",
    status: "ongoing",
    schedule: [],
    winner: null,
    runnerUp: null,
    stats: null,
  },
  {
    id: "tour-005",
    name: "Youth Summer Camp",
    description: "Training and games for young players.",
    details: {
      season: 2024,
      maxTeams: 10,
      matchesPerTeam: 6,
      totalOvers: 12,
      minAge: 8,
      maxAge: 14,
      halfBoundary: true,
      location: "Community Center",
    },
    teams: ["team-alpha"], // User joined
    organizer: "user-001",
    status: "completed",
    schedule: [],
    winner: "team-alpha",
    runnerUp: null,
    stats: null,
  },
];

export const mockUsers2 = [
  { id: "user-player-1", name: "Virat Kohli" },
  { id: "user-player-2", name: "Rohit Sharma" },
  { id: "user-player-3", name: "Jasprit Bumrah" },
  { id: "user-player-4", name: "MS Dhoni" },
  { id: "user-player-5", name: "Glenn Maxwell" },
  { id: "user-player-6", name: "Pat Cummins" },
  { id: "user-player-7", name: "Steve Smith" },
  { id: "user-player-8", name: "David Warner" },
];

export const dummyMatches = [
  {
    teamA: "Royal Challengers Bangaluru",
    teamB: "Chennai Super Kings",
    teamAPlayingXI: [
      "Virat Kohli",
      "Faf du Plessis",
      "Glenn Maxwell",
      "Dinesh Karthik",
      "Rajat Patidar",
      "Mahipal Lomror",
      "Wanindu Hasaranga",
      "Harshal Patel",
      "Josh Hazlewood",
      "Mohammed Siraj",
      "Shahbaz Ahmed",
    ],
    teamBPlayingXI: [
      "Ruturaj Gaikwad",
      "Devon Conway",
      "Moeen Ali",
      "Ben Stokes",
      "MS Dhoni",
      "Ravindra Jadeja",
      "Shivam Dube",
      "Deepak Chahar",
      "Maheesh Theekshana",
      "Mukesh Choudhary",
      "Tushar Deshpande",
    ],
    uid: "19234kaslfh2139",
    overs: 20,
    status: "completed",
    venue: "M. Chinnaswamy Stadium, Bengaluru",
    tossWinner: "Royal Challengers Bangaluru",
    tossDecision: "bat",
    highlights: [
      {
        time: new Date("2025-05-10T19:30:00Z"),
        title: "Kohli hits a stunning six",
        description: "Virat Kohli smashes a 95m six over long-on.",
        videoUrl: "https://example.com/video/kohli_six",
      },
    ],
    category: "T20",
    umpires: ["Nitin Menon", "Kumar Dharmasena"],
    matchReferee: "Javagal Srinath",
    startTime: new Date("2025-05-10T19:00:00Z"),
    endTime: new Date("2025-05-10T22:30:00Z"),
    innings: [
      {
        battingTeam: "Royal Challengers Bangaluru",
        bowlingTeam: "Chennai Super Kings",
        totalRuns: 182,
        totalWickets: 6,
        overs: 20,
        balls: [],
        inningNumber: 1,
        status: "completed",
      },
      {
        battingTeam: "Chennai Super Kings",
        bowlingTeam: "Royal Challengers Bangaluru",
        totalRuns: 178,
        totalWickets: 8,
        overs: 20,
        balls: [],
        inningNumber: 2,
        status: "completed",
      },
    ],
  },
];

export const playerStats = {
  matchesPlayed: 15,
  runsScored: 750,
  wicketsTaken: 8,
  fifties: 5,
  hundreds: 1,
  strikeRate: 145.7,
  average: 50.0,
  bestBowling: "4/25",
  catches: 12,
};

export const teamStats = {
  matchesPlayed: 20,
  matchesWon: 14,
  matchesLost: 5,
  matchesTied: 1,
  winRate: "70%",
  totalRunsScored: 2500,
  totalWicketsTaken: 120,
  averageScore: 125,
  highestScore: 210,
};

export const teams: TeamProps[] = [
  {
    id: "team1",
    name: "Mumbai Strikers",
    abbreviation: "MSK",
    description: "A local cricket team representing Mumbai.",
    address: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    owner: "user1",
    players: ["user2", "user3", "user4", "user5"],
    banner: "/img/mi-banner.png",
    logo: "/img/mi-logo.png",
    captain: "user2",
    type: "local",
    createdAt: new Date(),
    updatedAt: new Date(),
    isRecruiting: true,
    joinRequests: ["user10", "user11"],
  },
  {
    id: "team2",
    name: "Delhi Daredevils",
    abbreviation: "DD",
    description: "A college-level cricket squad from Delhi University.",
    address: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
    },
    owner: "user6",
    players: ["user7", "user8", "user9", "user10"],
    banner: "/img/mi-banner.png",
    logo: "/img/mi-logo.png",
    captain: "user7",
    type: "college",
    createdAt: new Date(),
    updatedAt: new Date(),
    isRecruiting: false,
    joinRequests: [],
  },
  {
    id: "team3",
    name: "Bangalore Blasters",
    abbreviation: "BBL",
    description: "Corporate cricket type from Bangalore IT Park.",
    address: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
    },
    owner: "user12",
    players: ["user13", "user14", "user15", "user16"],
    banner: "/img/mi-banner.png",
    logo: "/img/mi-logo.png",
    captain: "user13",
    type: "corporate",
    createdAt: new Date(),
    updatedAt: new Date(),
    isRecruiting: true,
    joinRequests: ["user17"],
  },
  {
    id: "team4",
    name: "Chennai Chargers",
    abbreviation: "CC",
    description: "Famous club type from Chennai.",
    address: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    owner: "user18",
    players: ["user19", "user20", "user21", "user22"],
    banner: "/img/mi-banner.png",
    logo: "/img/mi-logo.png",
    captain: "user19",
    type: "club",
    createdAt: new Date(),
    updatedAt: new Date(),
    isRecruiting: false,
    joinRequests: [],
  },
  {
    id: "team5",
    name: "Hyderabad Hurricanes",
    abbreviation: "HYH",
    description: "An energetic cricket squad with players from different colleges.",
    address: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    owner: "user23",
    players: ["user24", "user25", "user26", "user27"],
    banner: "/img/mi-banner.png",
    logo: "/img/mi-logo.png",
    captain: "user24",
    type: "others",
    createdAt: new Date(),
    updatedAt: new Date(),
    isRecruiting: true,
    joinRequests: ["user28", "user29"],
  },
];
